### ISSUE TITLE
Request to add requirements.txt

### ISSUE THREAD

**Issue by Michael-Nath-HS** [thedoge42/scibowl-stats#1]
Hey Geoffrey, 

I'm trying to use your stats script along with my Discord bot, and it seems that you haven't listed the dependencies that your script uses. Could you please upload a `requirements.txt` that has the dependencies and their versions listed. Thanks!

**Comment by geoffrey-wu** [comment]
Hello,

Thank you for pointing that out. I went ahead and added a requirements.txt file, as well as instructions in the readme

Geoffrey
